service: default
runtime: nodejs22
instance_class: F1

automatic_scaling:
  max_idle_instances: 1
  min_idle_instances: 0
  max_pending_latency: 10s
  max_instances: 1
  min_instances: 0

env_variables:
  NODE_ENV: production

